apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ius4f3ewv-dotnet-basic 
  janus-idp.io/tekton: ius4f3ewv-dotnet-basic
  backstage.io/kubernetes-id: ius4f3ewv-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ius4f3ewv-dotnet-basic
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml